# Constants for the accounts app

PROFILE_MIDDLE_INITIAL_MAX_LENGTH = 1
PROFILE_ADDRESS_MAX_LENGTH = 200

PROFILE_PHONE_NUMBER_MAX_LENGTH = 10
PROFILE_NUMBER_TYPE_MAX_LENGTH = 30

PHONE_NUMBER_TYPE_PLACEHOLDER = 'Home, Work, Cell, etc.'
EMAIL_PLACEHOLDER = 'myemail@example.com'

USER_CREATION_TITLE = 'Create a New User'

PHONE_NUMBER_FORMSET_MIN_NUM = 1
PHONE_NUMBER_FORMSET_EXTRA = 0

SIGNUP_ERROR_MESSAGE = 'Error entering information. Please correct errors below.'
