# Constants for the accounts app

PROFILE_MIDDLE_INITIAL_MAX_LENGTH = 1
PROFILE_ADDRESS_MAX_LENGTH = 200

PROFILE_PHONE_NUMBER_MAX_LENGTH = 9
PROFILE_NUMBER_TYPE_MAX_LENGTH = 30

PHONE_NUMBER_TYPE_PLACEHOLDER = 'Home, Work, Cell, etc.'
EMAIL_PLACEHOLDER = 'myemail@example.com'

USER_CREATION_TITLE = 'Create a New User'
