# Constants used in Manufacturer app.

MANUFACTURER_NAME_MAX_LENGTH = 100
MANUFACTURER_ADDRESS_MAX_LENGTH = 200

MANUFACTURER_PHONE_MAX_LENGTH = 10
MANUFACTURER_PHONE_TYPE_MAX_LENGTH = 30

PHONE_NUMBER_TYPE_PLACEHOLDER = 'HR, Headquarters, Customer Service, etc.'

CHOOSE_MANUFACTURER_TITLE = 'Choose A Pre-existing Manufacturer'
ADD_MANUFACTURER_TITLE = 'Add A New Manufacturer'

PHONE_NUMBER_MIN_NUM = 1
PHONE_NUMBER_EXTRA = 0
