# Constants for the powertain app

POWERTRAIN_MODEL_NUMBER_MAX_LENGTH = 20

POWERTRAIN_DRIVETRAIN_MAX_LENGTH = 100

CHOOSE_POWERTRAIN_TITLE = 'Choose Pre-Existing PowerTrain'
ADD_POWERTRAIN_TITLE = 'Add A New PowerTrain'