# Constants for Vehicle app

VEHICLE_TYPE_MAX_LENGTH = 100

SEDAN_CLASS_MAX_LENGTH = 50

TRUCK_BED_LENGTH_MAX_DIGITS = 6
TRUCK_BED_LENGTH_DECIMAL_PLACES = 2
TRUCK_BED_WIDTH_MAX_DIGITS = 6
TRUCK_BED_WIDTH_DECIMAL_PLACES = 2

COUPE_TOP_STYLE_MAX_LENGTH = 100

VEHICLE_TYPE_PLACEHOLDER = 'Sedan, SUV, Toyate, 4-Door, Red, etc.'

CHOOSE_VEHICLE_TITLE = 'Choose A Pre-existing Vehicle'
ADD_VEHICLE_TITLE = 'Add A New Vehicle'
